apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: scene-stealer
  name: scene-stealer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: scene-stealer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: scene-stealer
      name: scene-stealer
    spec:
      containers:
      - image: rainist/scene-stealer:1.0.0
        imagePullPolicy: IfNotPresent
        name: scene-stealer
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: scene-stealer
  name: scene-stealer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: scene-stealer
  sessionAffinity: None
  type: ClusterIP
